#!/usr/bin/env python3
"""Generate CATALOG.md from hub plus GitHub's public dsh-plugin topic."""
import json, re, sys, urllib.request, datetime

def fetch(url, token=None):
    req = urllib.request.Request(url, headers={"User-Agent": "awesome-dsh-sync", "Accept": "application/json"})
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.load(r)

def fetch_topic_repos(token=None):
    """Fetch public repositories tagged with GitHub's dsh-plugin topic."""
    repos = []
    for page in range(1, 11):
        data = fetch(
            f"https://api.github.com/search/repositories?q=topic%3Adsh-plugin&per_page=100&page={page}",
            token,
        )
        items = data.get("items", [])
        repos.extend(items)
        if not items or len(repos) >= data.get("total_count", len(repos)):
            break
    unique = {}
    for repo in repos:
        key = (repo.get("html_url") or repo.get("full_name") or "").rstrip("/").lower()
        if key:
            unique[key] = repo
    return list(unique.values())

# Public-facing catalog: drop internal program repos, rewrite notes referencing the test phase.
DROP_REPOS = {"group-chat-diary", "onboarding", "review-panel", "dsh-club"}
NOTE_REWRITES = {
    "issues": "官方 issue 反馈专用仓库（问题追踪）",
    "dsh-sfw": "防社死 WIP：遮挡敏感界面内容",
    "dsh-desktop-tools": "DSH 桌面工具集：一键启动、自动升级、开机自启、PWA 可安装补丁",
    "context-doctor": "上下文注入审计：指令链/技能目录/工具 schema 的 token 成本量化 + 重复/冲突检测 + 裁剪建议（Web 圆环 + context_audit）",
}
NAME_REWRITES = {
    "context-doctor": "dsh-context-doctor",
}
URL_REWRITES = {
    "context-doctor": "https://github.com/Zhenyu98/dsh-context-doctor",
    "dsh-island": "https://github.com/ChuanTianML/dsh-island",
}

# ===== Curated additions: repos missing from the dsh-plugin topic search =====
# (no topic, or beyond the search API's 1000-result cap). They flow into the 🌐
# section so they stay discoverable in CATALOG.md and the site store.
EXTRA_TOPIC_REPOS = [
    {"full_name": "yauntyour/DSH-Multimodal", "name": "DSH-Multimodal",
     "html_url": "https://github.com/yauntyour/DSH-Multimodal",
     "description": "DSH 多模态输入插件：按文件类型（图片/视频/音频）配置独立处理模型链，文件先转成 Prompt Tokens 再交给纯文本会话模型"},
    {"full_name": "Hyna-hla/harness-remote", "name": "harness-remote",
     "html_url": "https://github.com/Hyna-hla/harness-remote",
     "description": "第三方 DeepSeek Harness 手机遥控端：局域网/cpolar 连接、扫码自动连接、流式聊天、审批横幅与后台推送"},
    {"full_name": "ThreeBody6666/dsh-im-hub", "name": "dsh-im-hub",
     "html_url": "https://github.com/ThreeBody6666/dsh-im-hub",
     "description": "多平台 IM 网关：飞书（Lark）长连接、企业微信加密回调、Telegram 长轮询；GUI 可视化设置"},
    {"full_name": "SpookySandwich/dsh-smooth-stream", "name": "dsh-smooth-stream",
     "html_url": "https://github.com/SpookySandwich/dsh-smooth-stream",
     "description": "给 DeepSeek Harness 加入更好的流式文字动画"},
    {"full_name": "lbh1nb/dsh-plugins", "name": "lbh1nb/dsh-plugins",
     "html_url": "https://github.com/lbh1nb/dsh-plugins",
     "description": "DSH 插件合集：会话归档（dsh-session-archive）、附件上传（dsh-attachment-upload）、插话按钮（dsh-steer-button）等输入与会话管理插件"},
    {"full_name": "Optim-Agent/dsh-plans", "name": "dsh-plans",
     "html_url": "https://github.com/Optim-Agent/dsh-plans",
     "description": "计划先行 Agent 预设：把仓库变更调研沉淀为 dsh-plans/ 下可追溯的 Markdown 计划，经 reviewer/criticizer 子代理多轮打磨，再作为 DSH goal 按验证清单执行"},
    {"full_name": "nyantused-cpun/folio", "name": "folio",
     "html_url": "https://github.com/nyantused-cpun/folio",
     "description": "Folio（兰亭）：咨询文档生成引擎（接案 → 记忆 → 方法论 → 交付物 → 凭证）的原生 DSH 插件栈：15 个工具、会话协议事件、L0 防护、Agent 预设"},
    {"full_name": "sjh9714/dsh-movein", "name": "dsh-movein",
     "html_url": "https://github.com/sjh9714/dsh-movein",
     "description": "一条命令把整套 Claude Code 配置迁入 DSH：技能、MCP 服务器、hooks、子代理与权限规则，附 dry-run 迁移清单与迁移差异报告"},
    {"full_name": "SailingLoong/loongport-dsh", "name": "loongport-dsh",
     "html_url": "https://github.com/SailingLoong/loongport-dsh",
     "description": "多站点中转服务商接入：签名目录（身份、地址、模型）、Settings → LoongPort 服务商与 API Key 配置页、OpenAI 兼容路由"},
    {"full_name": "toolclub/agent_team_gui", "name": "dsh-agent-team-gui",
     "html_url": "https://github.com/toolclub/agent_team_gui",
     "description": "可复用 Agent 小队：每个成员独立配置 provider/model 路由与工具策略，支持串行/并行派单、spawn/fork/chain 上下文模式和 Web 管理面板"},
    {"full_name": "Khellendros97/dsh-better-model-selector", "name": "dsh-better-model-selector",
     "html_url": "https://github.com/Khellendros97/dsh-better-model-selector",
     "description": "将输入框模型选择器拆成「可搜索 + 收藏」的下拉选单和「推理强度滑动条」，支持 Ctrl+P / Ctrl+T 快速切换"},
    {"full_name": "xuboboo/dsh-gui", "name": "dsh-gui",
     "html_url": "https://github.com/xuboboo/dsh-gui",
     "description": "DeepSeek Harness 第三方 Windows 桌面客户端：原生窗口、品牌主题与启动动画、启动崩溃修复、Token 用量统计"},
    {"full_name": "ChuanTianML/dsh-open-with", "name": "dsh-open-with",
     "html_url": "https://github.com/ChuanTianML/dsh-open-with",
     "description": "从 DSH Web UI 的已登记工作区列表中，使用自动检测或手动配置的本机编辑器、终端或文件管理器打开目录，并记住浏览器首选目标"},
]



# ===== Manual topic categories (curated 2026-08-14; applied before keyword fallback) =====
TOPIC_MANUAL = {
    "01Virex/dsh-status-rotator": "界面与体验",
    "030611/dsh-telemetry-redactor": "安全与隐私",
    "030611/dsh-verification-receipt": "测试与诊断",
    "030611/qiushi-dsh-evidence-audit": "测试与诊断",
    "0sour/dsh-plugins": "开发与工程",
    "0xsline/awesome-deepseek-harness": "开发与工程",
    "0xsline/dsh-spotlight": "界面与体验",
    "yauntyour/dsh-for-vsc": "开发与工程",
    "ziyou979/dsh-llm-oauth": "模型与推理",
    "yauntyour/dsh-multimodal": "视觉与图像",
    "hyna-hla/harness-remote": "消息与通知",
    "threebody6666/dsh-im-hub": "消息与通知",
    "spookysandwich/dsh-smooth-stream": "界面与体验",
    "lbh1nb/dsh-plugins": "输入与提示词",
    "optim-agent/dsh-plans": "Agent 与自动化",
    "nyantused-cpun/folio": "研究与知识",
    "sjh9714/dsh-movein": "开发与工程",
    "sailingloong/loongport-dsh": "模型与推理",
    "toolclub/agent_team_gui": "Agent 与自动化",
    "khellendros97/dsh-better-model-selector": "界面与体验",
    "xuboboo/dsh-gui": "桌面客户端",
    "strukto-ai/mirage": "开发与工程",
    "121103qwq/dsh-vision-sidecar": "视觉与图像",
    "147228/dsh-black-whale": "界面与体验",
    "147228/dsh-xiaoyao-skins": "界面与体验",
    "1475505/dsh-plugin-miliastra-toolbox": "趣味与娱乐",
    "15828148/dsh-portable-launcher": "桌面客户端",
    "1690834643/dsh-usage-dashboard": "成本与用量",
    "1a125/dsh-mcp-manager": "开发与工程",
    "1na-ko/dsh-hdc-bridge": "浏览器与远程",
    "384961890-ui/pawin-brain-deepseek-harness": "记忆与上下文",
    "918154429/dsh-codex-import": "开发与工程",
    "AIMFllyYS/dsh-operating-context": "记忆与上下文",
    "Acidmoon/DIzzy-DSH": "开发与工程",
    "AdamPlatin123/awesome-dsh-plugins": "开发与工程",
    "AdamPlatin123/dsh-tonghuashun": "界面与体验",
    "Alex-Yanggg/awesome-DSH-plugin": "开发与工程",
    "Alexis-fish/dsh-projects": "开发与工程",
    "AllenCX/dsh-quant-workspace": "数据与可视化",
    "AlliotTech/deepseek-harness-docker": "开发与工程",
    "Alyosha28/deep_option": "研究与知识",
    "Amengclass/dsh-memory": "记忆与上下文",
    "AnacondaKC/dsh-custom-css": "界面与体验",
    "AnacondaKC/dsh-douyin": "趣味与娱乐",
    "AnacondaKC/dsh-stock-market": "数据与可视化",
    "Andy8647/dsh-auto-approval": "Agent 与自动化",
    "AngelosZou/graphlint": "开发与工程",
    "Anionex/agent-vision-toolkit": "视觉与图像",
    "Anionex/dsh-computer-use": "Agent 与自动化",
    "Anionex/dsh-turn-rewind": "开发与工程",
    "Anionex/dsh-vision-toolkit": "视觉与图像",
    "AprilWizard/dsh-multi-cot": "模型与推理",
    "Areium/dsh-fail-logger": "测试与诊断",
    "Arnoldkevin/prismrelay-mcp": "视觉与图像",
    "ArtificialNotImbecile/dsh-context-taxonomy": "记忆与上下文",
    "Asaiuta/dsh-session-hub": "浏览器与远程",
    "Ayase34/gal-view": "界面与体验",
    "Bandersnatch0x/amber-protocol": "Agent 与自动化",
    "Bandersnatch0x/design-playbook": "开发与工程",
    "BeAChanger/dsh-openclaw-acp": "消息与通知",
    "Beants/dsh-trellis": "Agent 与自动化",
    "BiBoyang/dsh-eval-harness": "测试与诊断",
    "BiBoyang/dsh-im-bridge": "消息与通知",
    "Bleed00/dsh-claude-mem": "记忆与上下文",
    "BlockRunAI/dsh-clawrouter": "Agent 与自动化",
    "BrambleXu/dsh-annotate": "界面与体验",
    "BrambleXu/dsh-prompt-profile": "输入与提示词",
    "BrambleXu/dsh-revdiff": "开发与工程",
    "BruceWu1126/dsh-web-background": "界面与体验",
    "Buyi-wsgzg/dsh-sidechain": "界面与体验",
    "CanglongCl/dsh-web-review": "界面与体验",
    "ChenSheg/knowledge-from-literature-and-bilibili": "研究与知识",
    "Chi-hong22/dsh-latexcp": "输入与提示词",
    "Chi-hong22/dsh-mdbox": "输入与提示词",
    "Chinesezjc/dsh-interconnect": "Agent 与自动化",
    "ChisaAlter/Deepseek-Harness-Desktop": "桌面客户端",
    "ChuanTianML/dsh-island": "界面与体验",
    "ChuanTianML/dsh-open-with": "开发与工程",
    "ChuanTianML/dsh-share": "开发与工程",
    "Chungor/owlx-mcp": "数据与可视化",
    "Civitasv/dsh-plugin-colorscheme": "界面与体验",
    "CrazyShout/dsh-ssh-remote": "浏览器与远程",
    "DDDFXYqiming/Agent_Extensions": "开发与工程",
    "DGPisces/deepseek-harness-chatgpt": "模型与推理",
    "DTSFO/dsh-conversation-rewind": "开发与工程",
    "DTSFO/dsh-model-modes": "模型与推理",
    "Degurechaff57/dsh-openapi": "开发与工程",
    "Deklan-Deng/Dcode": "桌面客户端",
    "Demogorgon314/dsh-resume-plugin": "记忆与上下文",
    "Devin-AXIS/iPolloWork": "Agent 与自动化",
    "Dino6021/dsh-usage-cost": "成本与用量",
    "Dominic789654/awesome-deepseek-harness": "开发与工程",
    "Drifter-yh/dsh-tool-policy": "安全与隐私",
    "Easyhoov/deepseek-harness-desktop": "桌面客户端",
    "Elaina-real/dsh-tiered-approval": "Agent 与自动化",
    "Electricitysheep/dsh-handbook": "研究与知识",
    "Electricitysheep/dsh-tool-turbo": "模型与推理",
    "Elohia/pi-mm-vision": "视觉与图像",
    "Ericwong5021/deepseek-plugin-store": "开发与工程",
    "Ericwong5021/dsh-kanban": "开发与工程",
    "Ethanout/computer-use-plus": "Agent 与自动化",
    "EvilIrving/dsh-context-proxy": "记忆与上下文",
    "EvilIrving/dsh-proof": "测试与诊断",
    "EvilIrving/dsh-repro": "测试与诊断",
    "FantasyStarry/dsh-token-stats": "成本与用量",
    "Favio8/dsh-plugin-deepeye": "视觉与图像",
    "Fisfzy/ego-browser": "浏览器与远程",
    "Fisfzy/math-lean": "研究与知识",
    "Fisfzy/zotero-harvest": "研究与知识",
    "Fisfzy/zotero-wave-rag": "记忆与上下文",
    "Fishquito7/dsh-skill-viewer": "开发与工程",
    "Fishsb/dsh-prompt-enhancer": "输入与提示词",
    "FlashingChen/dsh-worktree": "开发与工程",
    "FlytoMAYDAY80/dsh-pet": "趣味与娱乐",
    "Flyvhidbwo/dsh-vision-proxy": "视觉与图像",
    "GengDaPeng/dsh-agent-message": "Agent 与自动化",
    "Ghost011118/dsh-balance-meter": "成本与用量",
    "GiantGKL/dsh-cost": "成本与用量",
    "GoalfyAI/goalfydata": "开发与工程",
    "GooodWei/context-vista": "记忆与上下文",
    "Gordonynh/dsh-plugin-codex-import": "开发与工程",
    "H1a3x/dsh-token-stats": "成本与用量",
    "HackSing/dsh-plugins": "开发与工程",
    "Han-1413141/dsh-cost-meter": "成本与用量",
    "Han-1413141/dsh-sticky-disclosure": "界面与体验",
    "HaoyueQin/deepseek-harness-desktop": "桌面客户端",
    "HarcoChen/dsh-vsc-integration": "开发与工程",
    "He2way/dsh-task-console": "界面与体验",
    "HeiGeAi/deepseek-harness-skin": "界面与体验",
    "HomophonicFate/rpg-maker-mac-skill": "趣味与娱乐",
    "HongzhongL/dsh-hotswap": "开发与工程",
    "HsiangNianian/dsh-auto-continue": "Agent 与自动化",
    "Hu9956/dsh-codex-provider": "模型与推理",
    "HuanLinOTO/dsh-plugin-aigc-canvas": "视觉与图像",
    "HuanLinOTO/dsh-plugin-anti-ads": "界面与体验",
    "HuanLinOTO/dsh-plugin-auto-blame": "输入与提示词",
    "HuanLinOTO/dsh-plugin-better-sidebar-plugin-office": "开发与工程",
    "HuanLinOTO/dsh-plugin-d399": "趣味与娱乐",
    "HuanLinOTO/dsh-plugin-interpreters": "开发与工程",
    "HuanLinOTO/dsh-plugin-mineru": "开发与工程",
    "HuanLinOTO/dsh-plugin-pet-rs": "趣味与娱乐",
    "HuanLinOTO/dsh-plugin-sleep": "开发与工程",
    "HuanLinOTO/dsh-plugin-spur": "趣味与娱乐",
    "HuanLinOTO/dsh-plugin-ya-workspace-sidebar": "界面与体验",
    "HuanLinOTO/dsh-plugin-yet-another-subagent": "Agent 与自动化",
    "Hyperionjust/Primordial-soup-": "记忆与上下文",
    "Hyperionjust/dsh-tool-underseal": "开发与工程",
    "InklingYoshi584/dsh-tool-hashline": "开发与工程",
    "Isekai-Mfu/dsh-mimo-vision-hint": "视觉与图像",
    "JasonJin2006/dsh-sound-effects-plugin": "趣味与娱乐",
    "Jelee0145/dsh-mem": "记忆与上下文",
    "Jesse-njx/dsh-chatnode-wechat": "消息与通知",
    "Jesse-njx/dsh-cowork": "开发与工程",
    "Jesse-njx/dsh-crosstalk": "Agent 与自动化",
    "Jesse-njx/dsh-memory": "记忆与上下文",
    "Jesse-njx/dsh-plugin-manager": "开发与工程",
    "Jesse-njx/dsh-plugin-manager-registry": "开发与工程",
    "Jesse-njx/dsh-polyglot": "模型与推理",
    "Jesse-njx/dsh-routines": "Agent 与自动化",
    "Jesse-njx/dsh-skillport": "开发与工程",
    "Jesse-njx/dsh-voice": "输入与提示词",
    "JimmyJin2006/dsh-skill-manager": "开发与工程",
    "Jinsong-Zhou/dsh-html-canvas": "界面与体验",
    "Jinsong-Zhou/safe-find-dsh-plugins": "开发与工程",
    "JustGenius-s/DSH-Decktop": "其他",
    "JustGenius-s/DSH-Desktop": "桌面客户端",
    "JustGenius-s/DSH-Plugs": "开发与工程",
    "KarlOfLaw/dsh-goal-mode-enhance": "界面与体验",
    "KarlOfLaw/dsh-side-chat": "界面与体验",
    "Karuisawa-Mrs/dsh-plugins": "开发与工程",
    "KeLearns/dsh-update-checker": "桌面客户端",
    "Kevoyuan/dsh-mac-vision": "视觉与图像",
    "KhanZou/Deepseek-Harness-as-Desktop": "桌面客户端",
    "KinGao294/dsh-skin": "界面与体验",
    "KirschBlutX/engineer-software": "开发与工程",
    "KitDoesIt/dsh-compaction-instant": "记忆与上下文",
    "KnCRJVirX/dsh-desktop": "桌面客户端",
    "Komeiji-Shiki/graycode-for-dsh": "其他",
    "KureKaruna/dsh-at": "输入与提示词",
    "LJH-snow/dsh-tool-github": "开发与工程",
    "LX2000WASD/dsh-web-plugin-manager": "开发与工程",
    "LaoYueHanNi/dsh-token-usage": "成本与用量",
    "LaplaceYoung/dsh-qq2006": "界面与体验",
    "LaplaceYoung/oh-my-dsh": "开发与工程",
    "Lbryany/dsh-codebuddy": "模型与推理",
    "Leawind/dsh-minecraft-dev": "趣味与娱乐",
    "Leeaoyin/dr-agent-skills": "开发与工程",
    "Lehmaning/dsh-randomuuid-polyfill": "开发与工程",
    "LiangYin233/dsh-model-config-sync": "模型与推理",
    "LingLambda/dsh-undo": "记忆与上下文",
    "LingyeSoul/dsh-rider": "浏览器与远程",
    "Liu-ty/dsh-balance-display": "成本与用量",
    "Lixiaoyiao/deepseek-harness-action": "开发与工程",
    "LnsiAxe/dsh-web-restart": "开发与工程",
    "LoftyTao/dsh-ui-workbench": "界面与体验",
    "Loong-wql/Build-HOS-mcp": "开发与工程",
    "LoserFox/distill": "开发与工程",
    "LoserFox/dsh-git-identity": "开发与工程",
    "LoserFox/telegram": "消息与通知",
    "LuZhouheng/dsh-gen3d": "视觉与图像",
    "Luaphes/dsh-plugins-market": "开发与工程",
    "Luaphes/dsh-web-attention-badge": "消息与通知",
    "Lum1104/dsh-browser": "浏览器与远程",
    "Lyn-77/ProMentor": "研究与知识",
    "MAXeaglet/dsh-bash-terminal": "开发与工程",
    "MC5lan/dsh-multimodal": "视觉与图像",
    "MOLAaaaaaaa/dsh-seismicx": "研究与知识",
    "MaimoryLab/dib": "开发与工程",
    "Mappedinfo/PlainDeck": "开发与工程",
    "MashedPotato817/dsh-git-plugin": "开发与工程",
    "MashedPotato817/dsh-tool-browser": "浏览器与远程",
    "MashedPotato817/dsh-tui": "终端与 TUI",
    "Meredith2328/dsh-sticky-note": "开发与工程",
    "MicroHEROX/dsh-exa-mcp": "浏览器与远程",
    "Mingxi2077/dsh-plugin-review": "测试与诊断",
    "MirDie/dsh-xai": "模型与推理",
    "Moeblack/deepseek-manners": "趣味与娱乐",
    "Moeblack/dsh-message-edit": "输入与提示词",
    "Moeblack/dsh-payload-capture": "测试与诊断",
    "Moeblack/dsh-prompt-studio": "输入与提示词",
    "Moeblack/dsh-skins": "界面与体验",
    "Mongfayi/dsh-local-filetree": "界面与体验",
    "Mongfayi/dsh-recall": "输入与提示词",
    "MoonShadow1976/chiral-pulse": "界面与体验",
    "MorGogh/widget-dock": "界面与体验",
    "MostlyHarmlessxyz/dsh-safe-web-fetch": "浏览器与远程",
    "Moximxxx/dsh-find-skill": "开发与工程",
    "MuziIsabel/dsh-win-notify": "消息与通知",
    "NEXTINDIE/DeepSeek-Harness-for-VS-Code": "开发与工程",
    "Nagi-ovo/dsh-ads": "趣味与娱乐",
    "Nagi-ovo/dsh-find-plugins": "开发与工程",
    "Nagi-ovo/dsh-visualize": "界面与体验",
    "NanmiCoder/dsh-agent-teams": "Agent 与自动化",
    "Nexus-Aethra/DSH-plugin-switch": "开发与工程",
    "NexusAgentX/dsh-mcp-adapter": "开发与工程",
    "NigelYao/dsh-view-modes": "界面与体验",
    "NoWint/Oh-My-DSH": "开发与工程",
    "Nunchakus888/dsh-turn-budget": "成本与用量",
    "Nwflower/dsh-chat-import": "开发与工程",
    "Nwflower/dsh-file-claim": "开发与工程",
    "Opr4Mp3r/deepseek-harness-plugin-from-scratch": "开发与工程",
    "PM-Shawn/Abu-Cowork": "桌面客户端",
    "PangYiMing/dsh-batch-regression": "测试与诊断",
    "PangYiMing/dsh-bisect-debug": "测试与诊断",
    "PangYiMing/dsh-browser-control": "浏览器与远程",
    "PangYiMing/dsh-mobile-control": "浏览器与远程",
    "PangYiMing/dsh-port-guard": "开发与工程",
    "PangYiMing/dsh-screenshot-diff": "测试与诊断",
    "PeanutsDou/peanut-dsh-plugin": "开发与工程",
    "PerryLink/dsh-auto-review": "Agent 与自动化",
    "PerryLink/dsh-background-agents": "Agent 与自动化",
    "PerryLink/dsh-checkpoint-rewind": "开发与工程",
    "PerryLink/dsh-claude-move": "开发与工程",
    "PerryLink/dsh-composer-history": "输入与提示词",
    "PerryLink/dsh-doublecheck": "测试与诊断",
    "PerryLink/dsh-github": "开发与工程",
    "PerryLink/dsh-lsp-actions": "开发与工程",
    "PerryLink/dsh-memento": "记忆与上下文",
    "PerryLink/dsh-output-styles": "界面与体验",
    "PerryLink/dsh-permission-rules": "安全与隐私",
    "PerryLink/dsh-plugin-guide": "开发与工程",
    "PerryLink/dsh-session-pin": "界面与体验",
    "PerryLink/dsh-skill-pack-security": "安全与隐私",
    "PicGo/dsh-plugin": "视觉与图像",
    "PivotStackIntelligence/dsh-github": "开发与工程",
    "PixLunaLab/dsh-plugin-pixluna": "趣味与娱乐",
    "Player-MINEPIG/dsh-llm-codex-oauth": "模型与推理",
    "PlutoKeating/dsh-lark-bot": "消息与通知",
    "Porphyrioon/ironlaw": "测试与诊断",
    "Proton1917/dsh-live-stats": "数据与可视化",
    "Qintsg/dsh-safe-delete": "开发与工程",
    "RNlao/dsh-wallpaper": "界面与体验",
    "RRRosmontis/dsh-qwen-mm": "视觉与图像",
    "RYun601/dsh-launcher": "桌面客户端",
    "RangeKing/vibemeter": "数据与可视化",
    "RealAlexandreAI/dsh-all-search": "浏览器与远程",
    "RealAlexandreAI/dsh-atuin": "开发与工程",
    "RealAlexandreAI/dsh-cloudflare-browser-run": "浏览器与远程",
    "RealAlexandreAI/dsh-nocturne-memory": "记忆与上下文",
    "Roy-oss1/dsh-lark": "消息与通知",
    "Ruler4396/dsh-launcher": "桌面客户端",
    "Ruler4396/dsh-launcher-lifetime": "桌面客户端",
    "STARDUSTLC666/dsh-calendar": "开发与工程",
    "STARDUSTLC666/dsh-dingtalk": "消息与通知",
    "STARDUSTLC666/dsh-email": "消息与通知",
    "STARDUSTLC666/dsh-slack": "消息与通知",
    "SakalioLabs/dsh-code-ide": "开发与工程",
    "Scorp1o117/dsh-plugin-marketplace": "开发与工程",
    "Scorp1o117/dsh-soul-md": "趣味与娱乐",
    "Scorp1o117/dsh-tdai-memory": "记忆与上下文",
    "Scorp1o117/dsh-tool-vision": "视觉与图像",
    "Sdongmaker/vpshub": "浏览器与远程",
    "SenmuuuuW/dsh-group-photo": "趣味与娱乐",
    "SepineTam/mcp-for-stata": "开发与工程",
    "Sev7een/ds-api-usage": "成本与用量",
    "SeverusZh/dsh-notify-windows": "消息与通知",
    "ShawnSiao/dsh-agent-eval": "测试与诊断",
    "ShawnSiao/dsh-credentials-keychain": "安全与隐私",
    "Shmilyol/dsh-skin": "界面与体验",
    "SiYue-ZO/dsh-translator": "开发与工程",
    "Simon314620/dsh-turn-index": "界面与体验",
    "Small-tailqwq/dsh-deep-whale": "界面与体验",
    "Small-tailqwq/dsh-deepcel": "界面与体验",
    "Small-tailqwq/dsh-tps": "数据与可视化",
    "SnowCrescenter-tech/dsh-desktop": "桌面客户端",
    "SnowCrescenter-tech/dsh-launcher": "桌面客户端",
    "SnowCrescenter-tech/dsh-milestone": "界面与体验",
    "Spirit4471/multimodal-bridge": "视觉与图像",
    "Spirtxiaoqi7/mindspace-dsh-session-memory": "记忆与上下文",
    "Starfie1d1272/dsh-builtin-toggles": "开发与工程",
    "Sunrisepeak/dsh-index": "开发与工程",
    "THU-MAIC/dsh-openmaic": "研究与知识",
    "TYEclipse/dsh-netdoctor": "测试与诊断",
    "TYEclipse/dsh-plugins-hub": "开发与工程",
    "TYEclipse/dsh-webfetch": "浏览器与远程",
    "TecFancy/dsh-deeptutor": "研究与知识",
    "TheChengXi/intent-flow": "开发与工程",
    "TheYoungChen/dsh-plugin-market": "开发与工程",
    "Thhoho/reSanity": "研究与知识",
    "TiankunDai/dsh-vision-LMstudio": "视觉与图像",
    "Tieboyh/dsh-session-search": "记忆与上下文",
    "TohsakaRIN521/dsh-academic-skill": "研究与知识",
    "Tokimorphling/deepseek-harness-rs": "开发与工程",
    "Tokimorphling/tokilake-ai-gateway": "模型与推理",
    "Totoro-qaq/Cobsidian": "记忆与上下文",
    "Toukaiteio/dsh-effort-tweak": "模型与推理",
    "Toukaiteio/dsh-plugin-installer": "开发与工程",
    "Towzai/dsh-memory": "记忆与上下文",
    "TtTRz/dsh-gatedflow": "Agent 与自动化",
    "TtTRz/dsh-wecom": "消息与通知",
    "TwotwoPiggy/dsh-balance": "成本与用量",
    "Tyan66666/billion-context-dsh": "记忆与上下文",
    "UynajGI/dsh-ssh": "浏览器与远程",
    "Very12345/sai": "桌面客户端",
    "Very12345/sai-dsh-plugins": "开发与工程",
    "Void0312Aurora/dsh-desktop-electron": "桌面客户端",
    "WSL043/dsh-codex-subscription": "模型与推理",
    "Wanbinyu/dsh-billing": "成本与用量",
    "Wanbinyu/dsh-plugin-git-inspect": "开发与工程",
    "WardLu/shadow-vision": "视觉与图像",
    "Wha1eChai/dsh-supervisor": "Agent 与自动化",
    "Wine-Red/dsh-prompt-stash": "输入与提示词",
    "XCNXNXNX/dsh-portable-tavern": "趣味与娱乐",
    "XYZ1024-alt/dsh-side-panel": "界面与体验",
    "XiLuovo/dsh-session-timeline": "界面与体验",
    "Xieweikang123/dsh-vision-bridge": "视觉与图像",
    "Xilin3/dsh-prompt-persona": "输入与提示词",
    "Xplore-LAB/dsh-plugin-asmemory": "记忆与上下文",
    "YELEBAI/dsh-plugin-marketplace": "开发与工程",
    "YJSoooooo/dsh-chrome": "浏览器与远程",
    "YYTbit/awesome-dsh-bridges": "开发与工程",
    "YYTbit/dsh-plugin-agent-dashboard": "Agent 与自动化",
    "YYTbit/dsh-plugin-auto-docs": "开发与工程",
    "YYTbit/dsh-plugin-claude-bridge": "开发与工程",
    "YYTbit/dsh-plugin-code-review": "测试与诊断",
    "YYTbit/dsh-plugin-codex-bridge": "开发与工程",
    "YYTbit/dsh-plugin-context-compressor": "记忆与上下文",
    "YYTbit/dsh-plugin-cost-tracker": "成本与用量",
    "YYTbit/dsh-plugin-meta-memory": "记忆与上下文",
    "YYTbit/dsh-plugin-opencode-bridge": "开发与工程",
    "YYTbit/dsh-plugin-pi-bridge": "开发与工程",
    "YYTbit/dsh-plugin-rag": "记忆与上下文",
    "YYTbit/dsh-plugin-vision-toolkit": "视觉与图像",
    "Yan-Zero/dsh-codex": "模型与推理",
    "Ychris12138/dsh-usage-stats": "成本与用量",
    "Yihong89/dsh-plugins": "开发与工程",
    "YinFengWindy/dsh-plugin-shiori-role": "趣味与娱乐",
    "YisfL/dsh-desktop": "桌面客户端",
    "Youngxj/dsh-ProjectModel": "开发与工程",
    "YunTaiHua/illusion-agent": "Agent 与自动化",
    "Yuuz12/dsh-vision-helper": "视觉与图像",
    "ZASENJC/dsh-plugins-store": "开发与工程",
    "ZBCs-StudioCr-CN/dsh-skill-manager": "开发与工程",
    "ZK-Andy/dsh-continual-evolve": "Agent 与自动化",
    "ZSeven-W/dsh-openpencil": "开发与工程",
    "ZeroHackz/OpenFlowFrames": "视觉与图像",
    "ZgblKylin/dsh-terminal": "终端与 TUI",
    "ZhuXinAI/sidesight": "视觉与图像",
    "a179-sanae/dsh-code-check": "测试与诊断",
    "acosmi/dsh-session-supervisor": "Agent 与自动化",
    "agent-plaza/agent-plaza": "Agent 与自动化",
    "agentic-control-plane/dsh-acp-plugin": "Agent 与自动化",
    "akira399/dsh-godot-skill": "趣味与娱乐",
    "akira399/dsh-plugin-publisher": "开发与工程",
    "akqwpeter-prog/dsh-media-skills": "视觉与图像",
    "alaliqing/claude-paper": "研究与知识",
    "ali-meoo/meoo-cli": "开发与工程",
    "alingalingling/ui-status-label": "界面与体验",
    "alison-xx/deepseek-harness-flow": "Agent 与自动化",
    "alooshxl/dsh-session-pins": "界面与体验",
    "ang-XWBWZ/Pwiki": "记忆与上下文",
    "ang-XWBWZ/dsh-approval-ai": "Agent 与自动化",
    "anweat/dsh-plugin-dev-guide": "开发与工程",
    "anweat/dsh-web-search-pro": "浏览器与远程",
    "aryswisnu/dsh-eval-regression": "测试与诊断",
    "asdf17128/dsh-doctor": "测试与诊断",
    "asdf17128/dshp": "开发与工程",
    "awesome-dsh-plugin/awesome-dsh-plugin": "开发与工程",
    "awesome-dsh-plugin/dsh-find-plugin": "开发与工程",
    "ayuanwong/deepseek-harness-ux": "界面与体验",
    "baixinghao/intent-gate": "Agent 与自动化",
    "ben7am1n/dsh-browser": "浏览器与远程",
    "ben7am1n/dsh-claude-marketplace": "开发与工程",
    "ben7am1n/dsh-deepseek-usage": "成本与用量",
    "ben7am1n/dsh-lens-lite": "测试与诊断",
    "ben7am1n/dsh-mcp-proxy": "开发与工程",
    "ben7am1n/dsh-memory": "记忆与上下文",
    "ben7am1n/dsh-review-skills": "开发与工程",
    "ben7am1n/dsh-security-scan": "安全与隐私",
    "ben7am1n/dsh-telegram": "消息与通知",
    "ben7am1n/dsh-webhook-bridge": "消息与通知",
    "benzhoupo/dsh-effort-config": "模型与推理",
    "bill9109/dsh-101": "研究与知识",
    "bill9109/dsh-conversation-share": "开发与工程",
    "bill9109/dsh-drag-and-drop": "输入与提示词",
    "bill9109/dsh-web-ui-notify": "消息与通知",
    "bill9109/dsh-webbridge": "模型与推理",
    "biociao/dsh-science": "研究与知识",
    "bitterSmilezzz/dsh-mac-desktop": "桌面客户端",
    "bitterSmilezzz/dsh-model-selector": "模型与推理",
    "bitterSmilezzz/dsh-skill-manager": "开发与工程",
    "blue-a11y/dsh-client-shortcuts": "输入与提示词",
    "boNeXY226/dsh-cost-chip": "成本与用量",
    "bobleer/deepseek-harness-plugin-mcp": "开发与工程",
    "bobleer/dsh-acp-for-bitfun": "Agent 与自动化",
    "bpc-oss/dsh-web-billing": "成本与用量",
    "bradeGithub/DSH-Plugins-Marketplace": "开发与工程",
    "bruc3van/awesome-dsh-plugin": "开发与工程",
    "bruc3van/dsh-desktop": "桌面客户端",
    "btspoony/dsh-advisor": "模型与推理",
    "btspoony/dsh-llm-fallbacks": "模型与推理",
    "btspoony/mstar-harness": "Agent 与自动化",
    "bugmaker2/dsh-plugin-template": "开发与工程",
    "cakeni/harness-whale": "趣味与娱乐",
    "causebefore/dsh-pomodoro": "开发与工程",
    "cccakeee/awesome-dsh-plugins": "开发与工程",
    "ccch1mneyyy/dsh-TUI": "终端与 TUI",
    "ccch1mneyyy/dsh-working-activity": "界面与体验",
    "ccq1/dsh-side-panel": "界面与体验",
    "cendaifeng/dsh-learn-everything": "研究与知识",
    "cesaryike/dsh-image-to-path": "视觉与图像",
    "chajiuqqq/dsh-claude-theme": "界面与体验",
    "chen-001/dsh-chat-width": "界面与体验",
    "chen-001/dsh-grok-tui": "终端与 TUI",
    "chushixixin/dsh-harness-mcp-server": "开发与工程",
    "chyra-moon/deepseek-harness-desktop": "桌面客户端",
    "citrusli2026/dsh-mobile-ui": "界面与体验",
    "cking000bigdemon/dsh-toolbelt": "开发与工程",
    "cnskycn/deepseek-harness-desktop": "桌面客户端",
    "codeAnqiang-ma/dsh-superpowers": "开发与工程",
    "coderPerseus/dsh-hub": "开发与工程",
    "cofy-x/axern": "开发与工程",
    "cogine-ai/marketplace": "开发与工程",
    "congchuanling-dot/DSH-Telegram-Relay": "消息与通知",
    "coppynight/dsh-doctor": "测试与诊断",
    "crayonlu/dsh-web-search-firecrawl": "浏览器与远程",
    "crayonlu/dsh-web-search-tavily": "浏览器与远程",
    "crystalWinter666/dsh-header-status": "界面与体验",
    "csiroqa/dsh-archive-viewer": "开发与工程",
    "csiroqa/dsh-backup-sync": "开发与工程",
    "csiroqa/dsh-command-opt": "输入与提示词",
    "csiroqa/dsh-hotkeys": "输入与提示词",
    "csiroqa/dsh-plugin-usage-report": "成本与用量",
    "csiroqa/dsh-schedule": "Agent 与自动化",
    "csyangwen/dsh-memory-evolve": "记忆与上下文",
    "cute-baobao/dsh-usage-meter": "成本与用量",
    "cyanseek/dsh-landscape": "开发与工程",
    "cyanseek/dsh-native-playbook": "研究与知识",
    "cyanseek/dsh-tool-chaos": "测试与诊断",
    "cyberlieflife/dsh-model-thinking": "模型与推理",
    "cyzlmh/dsh-pi-adapter": "开发与工程",
    "czzzlq/deepseek-harness-background": "界面与体验",
    "czzzlq/deepseek-harness-desktop": "桌面客户端",
    "dancingmemory/dskin": "界面与体验",
    "dbydd/dsh-onlyne": "消息与通知",
    "deepseek-ai/deepseek-harness": "开发与工程",
    "detpecca/DSH-Wiki": "研究与知识",
    "detpecca/dsh-llm-wiki": "记忆与上下文",
    "dingkaihu63/dsh-robotic-harness": "研究与知识",
    "dingyi222666/dsh-focus-chat": "界面与体验",
    "dingyi222666/dsh-session-notification": "消息与通知",
    "dongsheng123132/awesome-dsh-plugins": "开发与工程",
    "dongsheng123132/dsh-2origin": "测试与诊断",
    "dongsheng123132/dsh-action-parity": "测试与诊断",
    "dongsheng123132/dsh-benchmark": "测试与诊断",
    "dongsheng123132/dsh-cad-review": "测试与诊断",
    "dongsheng123132/dsh-capability-receipt": "测试与诊断",
    "dongsheng123132/dsh-cost": "成本与用量",
    "dongsheng123132/dsh-lineage": "测试与诊断",
    "dongsheng123132/dsh-narrative-ledger": "测试与诊断",
    "dongsheng123132/dsh-recovery-proof": "测试与诊断",
    "dongsheng123132/dsh-release-proof": "测试与诊断",
    "dongsheng123132/dsh-switch": "模型与推理",
    "dongsheng123132/task-passport": "Agent 与自动化",
    "drfccv/dsh-theme-neko": "界面与体验",
    "drscrewdriver/inferglow": "终端与 TUI",
    "dsh-external/awesome-dsh-plugins": "开发与工程",
    "dsh-external/dsh-STAGE": "输入与提示词",
    "dsh-external/dsh-STAR": "研究与知识",
    "dsh-external/dsh-agent-teams": "Agent 与自动化",
    "dsh-external/dsh-at-file": "输入与提示词",
    "dsh-external/dsh-automation": "Agent 与自动化",
    "dsh-external/dsh-better-browser": "浏览器与远程",
    "dsh-external/dsh-book2skill": "开发与工程",
    "dsh-external/dsh-custom-tool": "开发与工程",
    "dsh-external/dsh-daily-fortune": "趣味与娱乐",
    "dsh-external/dsh-daily-progress": "趣味与娱乐",
    "dsh-external/dsh-deeptag": "Agent 与自动化",
    "dsh-external/dsh-doctor": "测试与诊断",
    "dsh-external/dsh-ernie-image": "视觉与图像",
    "dsh-external/dsh-eye-care": "界面与体验",
    "dsh-external/dsh-fun-ticker": "数据与可视化",
    "dsh-external/dsh-fun-typewriter": "趣味与娱乐",
    "dsh-external/dsh-fun-weather": "趣味与娱乐",
    "dsh-external/dsh-longbridge": "数据与可视化",
    "dsh-external/dsh-notification": "消息与通知",
    "dsh-external/dsh-open-in-vscode": "开发与工程",
    "dsh-external/dsh-paddle-ocr": "视觉与图像",
    "dsh-external/dsh-pet-corner": "趣味与娱乐",
    "dsh-external/dsh-plannotator": "输入与提示词",
    "dsh-external/dsh-revive": "Agent 与自动化",
    "dsh-external/dsh-sentinel": "Agent 与自动化",
    "dsh-external/dsh-spotlight": "界面与体验",
    "dsh-external/dsh-voice-funasr": "输入与提示词",
    "dsh-external/dsh-webui-live-html": "界面与体验",
    "dsh-plugin/dsh-plugin.github.io": "开发与工程",
    "dsh-tui/dsh-tui": "终端与 TUI",
    "dyuan311/dsh-openai-codex-oauth": "模型与推理",
    "echo-escape/dsh-workbench": "开发与工程",
    "edwardyang0011/dsh-ui-skins": "界面与体验",
    "egnmosk/dsh-browser-bridge": "浏览器与远程",
    "emredeveloper/deepseek-harness-huggingface": "模型与推理",
    "entireyu/dsh-launcher": "桌面客户端",
    "erduotong/dsh-plugin-graph": "开发与工程",
    "f0909172434/dsh-plugin-verified-search": "浏览器与远程",
    "fakechris/dsh-harness-ops": "开发与工程",
    "fakechris/dsh-track": "开发与工程",
    "feiyang-dev/DeepSeek-Harness-Desktop": "桌面客户端",
    "fengzhiyushui/dsh-desktop-window": "桌面客户端",
    "fff122/dsh-agent-arcade": "趣味与娱乐",
    "fff122/dsh-prompt-presets": "输入与提示词",
    "fff122/dsh-research-notes": "研究与知识",
    "fff122/dsh-task-checklist": "开发与工程",
    "fishlikewater/dsh-mcp-manager": "开发与工程",
    "fishxcode/dsh-plugin-deepseek-balance": "成本与用量",
    "fly3366/DeepJIT": "Agent 与自动化",
    "forrestchang/dsh-multica-runtime": "开发与工程",
    "fountunt/dsh-session-cleaner": "开发与工程",
    "franksong2702/dsh-codex-connect": "模型与推理",
    "fuhefei/dsh-sentinel": "Agent 与自动化",
    "gameswu/dsh-plugin-background": "界面与体验",
    "ginuim/multi-screen-wireframe": "开发与工程",
    "gnulife/dsh-plugin-wechat": "消息与通知",
    "gordonlu/dsh-context-lens": "记忆与上下文",
    "green-dalii/dsh-plugin-dev-skill": "开发与工程",
    "green-dalii/dsh-shift-router": "模型与推理",
    "gxinxing/deepseek-harness-tui": "终端与 TUI",
    "gxpppp/dsh-search-mcp": "浏览器与远程",
    "hanelalo/browser-bridge": "浏览器与远程",
    "happyren/dsh-agent-messaging": "Agent 与自动化",
    "hashdiana/dsh-archived-sessions": "开发与工程",
    "hashdiana/dsh-token-usage": "成本与用量",
    "havingautism/dsh-deepresearch": "研究与知识",
    "havingautism/dsh-notebooks": "开发与工程",
    "havingautism/dsh-ultra-ui": "界面与体验",
    "hawkongz/doubao-vision-dsh": "视觉与图像",
    "haytham818/dsh-notify": "消息与通知",
    "hccccc01333/dsh-analytics": "成本与用量",
    "hccccc01333/dsh-eval": "测试与诊断",
    "hccccc01333/dsh-excel-chat": "开发与工程",
    "hccccc01333/dsh-excel-vera-plugin": "测试与诊断",
    "hccccc01333/dsh-report-html": "开发与工程",
    "hellodigua/dsh-emoji": "趣味与娱乐",
    "hellodigua/dsh-share": "开发与工程",
    "hellosz/dsh-ntfy": "消息与通知",
    "hellowind777/helloagents": "Agent 与自动化",
    "hikariming/dshfind": "研究与知识",
    "hisaniwo/dsh-ergonomics": "输入与提示词",
    "hnmrxz/dsh-plugin-deepseek-balance": "成本与用量",
    "hrhgit/deepseek-harness-plugin-manager": "开发与工程",
    "huashenglian/dsh-her-eyes": "视觉与图像",
    "huguangyu666/dsh-plugin-session-import": "开发与工程",
    "huiliyi37/dsh-tianshu-build": "终端与 TUI",
    "huiliyi37/dsh-tianshu-tui": "终端与 TUI",
    "humblebanana/dsh-record-replay": "Agent 与自动化",
    "humblebanana/open-record-replay": "Agent 与自动化",
    "hust-open-atom-club/oh-dsh": "开发与工程",
    "hyls9527/dsh-plugins": "记忆与上下文",
    "hyqhyq3/dsh-mcp-manager": "开发与工程",
    "icetomoyo/dsh_workflow": "Agent 与自动化",
    "icodesign/orbis": "浏览器与远程",
    "ilharp/dsh-tool-approval": "Agent 与自动化",
    "imetn/dsh-lark-bridge": "消息与通知",
    "inmny/dsh-git-bash": "开发与工程",
    "isolat-3k/dsh-kanban": "开发与工程",
    "iuikj/dsh-desktop": "桌面客户端",
    "jLeon-account/dsh-client-usage": "成本与用量",
    "jark006/RemoteOps": "浏览器与远程",
    "jasonsun29/ds-balance-card": "成本与用量",
    "jasper-zsh/dsh-plugin-llm-codex": "模型与推理",
    "jasper-zsh/dsh-plugin-provider-quota": "成本与用量",
    "jelly-000/dsh-balance-monitor": "成本与用量",
    "jiesou/dsh-stream-rules": "Agent 与自动化",
    "jihongboo/dsh-apple-mode": "开发与工程",
    "jinhuang712/dsh-survey": "输入与提示词",
    "jiruidai/dsh-meta-orchestrator": "Agent 与自动化",
    "jorinyang/dsh-doctor": "测试与诊断",
    "joyfoxai/dsh-eco-router": "模型与推理",
    "jumpserver-east/jumpserver-dsh": "开发与工程",
    "junhongchashui/dsh-plugin-web-access": "浏览器与远程",
    "kalynnka/vscode-deepseek-harness": "开发与工程",
    "kangjinghang/dsh-xueqiu": "数据与可视化",
    "karuboniru/dsh-approval-guardian": "Agent 与自动化",
    "kazecreator/dsh-plugins": "开发与工程",
    "keepermttl/dsh-archive-viewer": "开发与工程",
    "kejixiaoliang/awesome-dsh-plugins": "开发与工程",
    "kelai141/dsh-client-ui-responsive": "界面与体验",
    "kelai141/dsh-host-web-compat": "开发与工程",
    "kelai141/dsh-mobile-apk": "桌面客户端",
    "kelai141/dsh-shell-termux": "开发与工程",
    "keleus/deepseek-pet": "趣味与娱乐",
    "kerwin2046/dsh-pin-recall": "记忆与上下文",
    "kevenxz/dsh-desktop": "桌面客户端",
    "kiim-wong/dsh-push": "消息与通知",
    "kingsunb/dsh-model-plus": "模型与推理",
    "kinyokun/dsh-session-import": "开发与工程",
    "knqiufan/powercontext-dsh": "记忆与上下文",
    "krislavten/ai-sdk-provider-dsh": "模型与推理",
    "kyorakuyk/dsh-desktop": "桌面客户端",
    "lakeofsky347/dsh-vision": "视觉与图像",
    "leechen298/Code2Skill": "开发与工程",
    "lehhair/dsh-diff-viewer": "界面与体验",
    "lehhair/dsh-mobile": "界面与体验",
    "lehhair/dsh-split-panes": "界面与体验",
    "levi-qiao/dsh-plugin-longgraph": "Agent 与自动化",
    "lhh010/dsh-bash-encoding": "开发与工程",
    "lhh010/dsh-input-history": "输入与提示词",
    "lhh010/dsh-minigames": "趣味与娱乐",
    "lhh010/dsh-paste-input": "输入与提示词",
    "lhh010/dsh-ui-progress": "界面与体验",
    "lhh010/dsh-ui-whale": "趣味与娱乐",
    "lhmd/dsh-director-toolkit": "开发与工程",
    "lhmd/dsh-promotion-toolkit": "开发与工程",
    "libukai/awesome-deepseek-harness": "研究与知识",
    "liguobao/dsh-desktop": "桌面客户端",
    "like-study1/Oh-My-DSH": "开发与工程",
    "lin-cheng-lab/dsh-deepseek-balance": "成本与用量",
    "lin-cheng-lab/dsh-plugin-doctor": "测试与诊断",
    "lin-cheng-lab/dsh-reloader": "开发与工程",
    "linhay/harmony-next.skills": "开发与工程",
    "lispking/git-skills": "开发与工程",
    "litestartup-com/litestartup-skills": "开发与工程",
    "liustack/modlens": "视觉与图像",
    "liustack/modsearch": "浏览器与远程",
    "liuup/dsh-latex-tools": "输入与提示词",
    "ljsysfurryACE/AgentFrame-v3": "Agent 与自动化",
    "lonelymoon87/dsh-code-intel": "开发与工程",
    "lonelymoon87/dsh-gitflow": "开发与工程",
    "lonelymoon87/dsh-guardian": "安全与隐私",
    "lonelymoon87/dsh-specflow": "开发与工程",
    "lonelymoon87/dsh-vscode": "开发与工程",
    "longyu065/dsh-desktop": "桌面客户端",
    "longyu065/dsh-session-index": "记忆与上下文",
    "longyu065/dsh-theme-ti": "界面与体验",
    "lordqyxz/dsh-ark-quota": "成本与用量",
    "lordship12138-crypto/dsh-plugin-dedup": "开发与工程",
    "loudMore/dsh-drop-to-path": "输入与提示词",
    "lujoai/Lujo-MCP": "测试与诊断",
    "lunw/shopline-ai-toolkit-dsh": "开发与工程",
    "lwmxiaobei/dsh-plugins": "开发与工程",
    "lxj808624/dsh-tool-git": "开发与工程",
    "lynkas/dsh-think-flow-flow": "界面与体验",
    "lynx-gt/dsh-subagent-cwd": "Agent 与自动化",
    "lynx-gt/dsh-subagent-tools": "Agent 与自动化",
    "lzszq/dsh-scholar": "研究与知识",
    "makuralymi/dsh-webUI-Glass-Theme": "界面与体验",
    "malevrigns/dsh-session-stars": "开发与工程",
    "mario03690/dsh-netcafe": "开发与工程",
    "minatoAI/jina-dsh-plugin": "浏览器与远程",
    "misakimiku2/dsh-cost-display": "成本与用量",
    "mitao-su/dsh-playwright-cli": "浏览器与远程",
    "mitao-su/dsh-playwright-native": "浏览器与远程",
    "moduqishi/GrassVison": "视觉与图像",
    "moduqishi/dsh-open-in-finder": "开发与工程",
    "moduqishi/dsh-opencode-usage": "成本与用量",
    "modusensus/dsh-mneme": "记忆与上下文",
    "morlay/session-persistence-rdb": "开发与工程",
    "morluto/flameox": "测试与诊断",
    "morluto/gitcontribute": "测试与诊断",
    "morluto/internalcot": "模型与推理",
    "morluto/jacobian": "研究与知识",
    "morluto/leantoken": "开发与工程",
    "morluto/rea": "开发与工程",
    "morluto/smokinggun": "测试与诊断",
    "moxisuki/dsh-lan": "浏览器与远程",
    "mrbbbaixue/dsh-desktop": "桌面客户端",
    "nightwhale-dev/nightwhale": "测试与诊断",
    "nowledge-co/nowledge-mem-deepseek-harness": "记忆与上下文",
    "nutshellai-tech/mobius": "Agent 与自动化",
    "octoparse/agent-skills": "开发与工程",
    "oil-oil/dsh-vision": "视觉与图像",
    "oitsukiii/deepseek-harness-lan": "浏览器与远程",
    "omdsh-dev/7d7d": "趣味与娱乐",
    "omdsh-dev/DSH-better-sidebar": "界面与体验",
    "omdsh-dev/Qwen-MM-Plugins": "视觉与图像",
    "omdsh-dev/dsh-advisor": "模型与推理",
    "omdsh-dev/dsh-annotation": "输入与提示词",
    "omdsh-dev/dsh-at-file": "输入与提示词",
    "omdsh-dev/dsh-auto-chess": "趣味与娱乐",
    "omdsh-dev/dsh-book2skill": "开发与工程",
    "omdsh-dev/dsh-custom-tool": "开发与工程",
    "omdsh-dev/dsh-daily-fortune": "趣味与娱乐",
    "omdsh-dev/dsh-daily-progress": "趣味与娱乐",
    "omdsh-dev/dsh-data-agent": "开发与工程",
    "omdsh-dev/dsh-deep-research": "研究与知识",
    "omdsh-dev/dsh-ernie-image": "视觉与图像",
    "omdsh-dev/dsh-fun-ticker": "数据与可视化",
    "omdsh-dev/dsh-fun-typewriter": "趣味与娱乐",
    "omdsh-dev/dsh-fun-weather": "趣味与娱乐",
    "omdsh-dev/dsh-genui": "界面与体验",
    "omdsh-dev/dsh-github-integration": "开发与工程",
    "omdsh-dev/dsh-gomoku": "趣味与娱乐",
    "omdsh-dev/dsh-hub": "开发与工程",
    "omdsh-dev/dsh-hub-workshop": "开发与工程",
    "omdsh-dev/dsh-inspect": "测试与诊断",
    "omdsh-dev/dsh-kb-sieve": "记忆与上下文",
    "omdsh-dev/dsh-lark": "消息与通知",
    "omdsh-dev/dsh-llm-fallbacks": "模型与推理",
    "omdsh-dev/dsh-longbridge": "数据与可视化",
    "omdsh-dev/dsh-mnemon": "记忆与上下文",
    "omdsh-dev/dsh-mygo": "开发与工程",
    "omdsh-dev/dsh-notification": "消息与通知",
    "omdsh-dev/dsh-open-in-vscode": "开发与工程",
    "omdsh-dev/dsh-paddle-ocr": "视觉与图像",
    "omdsh-dev/dsh-pet-corner": "趣味与娱乐",
    "omdsh-dev/dsh-plugin-check": "测试与诊断",
    "omdsh-dev/dsh-plugin-dev": "开发与工程",
    "omdsh-dev/dsh-plugin-skills": "开发与工程",
    "omdsh-dev/dsh-revive": "Agent 与自动化",
    "omdsh-dev/dsh-science": "开发与工程",
    "omdsh-dev/dsh-scout": "开发与工程",
    "omdsh-dev/dsh-security-audit": "安全与隐私",
    "omdsh-dev/dsh-session-health": "测试与诊断",
    "omdsh-dev/dsh-tool-browser": "浏览器与远程",
    "omdsh-dev/dsh-tool-calculator": "开发与工程",
    "omdsh-dev/dsh-tool-csv": "开发与工程",
    "omdsh-dev/dsh-tool-diff": "开发与工程",
    "omdsh-dev/dsh-tool-encoding": "开发与工程",
    "omdsh-dev/dsh-tool-json": "开发与工程",
    "omdsh-dev/dsh-tool-markdown": "开发与工程",
    "omdsh-dev/dsh-tool-regex": "开发与工程",
    "omdsh-dev/dsh-tool-schema": "开发与工程",
    "omdsh-dev/dsh-tool-stat": "开发与工程",
    "omdsh-dev/dsh-tool-time": "开发与工程",
    "omdsh-dev/dsh-toolkit": "开发与工程",
    "omdsh-dev/dsh-voice-funasr": "输入与提示词",
    "omdsh-dev/ex-setting": "开发与工程",
    "omdsh-dev/fabric": "开发与工程",
    "omdsh-dev/omdsh": "开发与工程",
    "omdsh-dev/omdsh-runtime": "开发与工程",
    "omdsh-dev/plugin-template": "开发与工程",
    "omdsh-dev/sandbox-micro": "开发与工程",
    "omdsh-dev/sandbox-mxc": "开发与工程",
    "omdsh-dev/sandbox-nono": "开发与工程",
    "omdsh-dev/session-teleport": "浏览器与远程",
    "omdsh-dev/toybox": "趣味与娱乐",
    "omdsh-dev/web-components": "开发与工程",
    "openHacking/pptkit-presentation": "开发与工程",
    "openguardrails/openguardrails": "安全与隐私",
    "openma-ai/deepseek-harness-acp": "Agent 与自动化",
    "openma-ai/deepseek-harness-tui": "终端与 TUI",
    "openma-ai/deepseek-harness-typescript-sdk": "开发与工程",
    "openma-ai/open-managed-agents": "Agent 与自动化",
    "opensetk/dsh-xiaohei": "界面与体验",
    "ophielel/dsh-devkit": "开发与工程",
    "orriduck/dsh-tui": "终端与 TUI",
    "oslook/awesome-dsh-plugins": "开发与工程",
    "paean-ai/8x-skills": "趣味与娱乐",
    "paean-ai/deeptide": "桌面客户端",
    "pandashere/dsh-codex-bridge": "模型与推理",
    "pandashere/dsh-kimi-bridge": "模型与推理",
    "pandashere/dsh-self-control-guard": "开发与工程",
    "peach0x33a/dsh-open-browser": "浏览器与远程",
    "pinch-eng/dsh-audio-dub": "开发与工程",
    "pingfanfan/hello-dsh": "开发与工程",
    "pinkllo/dsh-reasoning-translator": "模型与推理",
    "pulseaiclub/phi": "Agent 与自动化",
    "qing3a/dsh-event-auditor": "测试与诊断",
    "qing3a/dsh-plugin-verify": "测试与诊断",
    "qing3a/dsh-tray": "桌面客户端",
    "qingchunnh/dsh-desktop": "桌面客户端",
    "qingzhuo-cn/agent-fix": "开发与工程",
    "qiqikuaidianpao/mypet": "趣味与娱乐",
    "qizhen2021/dsh-plugin-vision": "视觉与图像",
    "quan2005/dsh-plugin-jinji": "记忆与上下文",
    "qwased/dsh-web-search-duckduckgo": "浏览器与远程",
    "qyw233/dsh-deeplink": "开发与工程",
    "rabbitknight/dsh-tui": "终端与 TUI",
    "radaren/dsh-auth": "安全与隐私",
    "railgun0325/dsh-phone": "浏览器与远程",
    "rainforest888/dsh-plugins-raincode": "模型与推理",
    "randerous/dsh-turn-budget": "Agent 与自动化",
    "randerous/dsh-turn-meta": "开发与工程",
    "renat3u/dsh-paseo": "开发与工程",
    "renat3u/dsh-web-archive": "界面与体验",
    "renat3u/tonghuashun-webui": "界面与体验",
    "reshuibuduo/tmcra-deepseek-harness-memory": "记忆与上下文",
    "rizkirmdhnnn/dsh-tool-notify": "消息与通知",
    "ropon/dsh-plugin-clawrouters": "模型与推理",
    "rsagacom/dsh-ajw": "开发与工程",
    "runzhliu/deepseek-harness-docker": "开发与工程",
    "rxa3c/chat2skill": "开发与工程",
    "rxh1999/dsh-jingle": "趣味与娱乐",
    "sakikoTGW/pack-agent": "开发与工程",
    "sakurarain1213/deepseek-harness-lite": "开发与工程",
    "sala003/dsh-tool-describe-image": "视觉与图像",
    "sandbaseai/sandbase-harness": "Agent 与自动化",
    "sandbaseai/sandbase-skills": "开发与工程",
    "schhaohao/dsh-file-explorer": "开发与工程",
    "securstack/securstack-dsh-plugin": "安全与隐私",
    "shaokeyibb/dsh-plugin-product-subagents": "Agent 与自动化",
    "shelken/dsh-co-authored-by": "开发与工程",
    "shi275773124/falsify-dsh": "测试与诊断",
    "shinelon/eyes-for-deepseek": "视觉与图像",
    "shiningsprk-arch/dsh-context-viewer": "记忆与上下文",
    "shuguang1994/project-blueprint": "开发与工程",
    "shujiTech/dsh-plugin-wepre": "开发与工程",
    "shyboy/dsh-k12-lesson-builder": "研究与知识",
    "sikwoxy/dsh-tool-reqpipe": "开发与工程",
    "simon300000/dsh-auto": "Agent 与自动化",
    "sindo-s/dsh-qq-bot": "消息与通知",
    "sisyphus-iambe/northstar-exam": "测试与诊断",
    "sjscy05/deepseek-harness-vision-plugin": "视觉与图像",
    "sjscy05/dsh-task-progress-notifier": "消息与通知",
    "sjscy05/matlab-modelsim-vivado-plugin": "开发与工程",
    "skitse/dsh-dev-actions": "开发与工程",
    "skyzhao1223/dsh-plugin-scaffold": "开发与工程",
    "sliverp/DeepSeek-harness-dingtalk": "消息与通知",
    "sliverp/DeepSeek-harness-lark": "消息与通知",
    "sliverp/DeepSeek-harness-qqbot": "消息与通知",
    "sliverp/DeepSeek-harness-wecom": "消息与通知",
    "sliverp/DeepSeek-harness-weixin": "消息与通知",
    "smanx/dsh-conversation-indicator": "界面与体验",
    "songqikong/dash": "Agent 与自动化",
    "spike-faye-lei/spike-faye-lei-dsh-skills": "开发与工程",
    "springbrand-lab/dsh-oauth-mcp-client": "开发与工程",
    "studyzy/dsh-suggest-prompt": "输入与提示词",
    "stushansusu/dsh-miku-skin": "界面与体验",
    "sublatesublate-design/dsh-doctor-windows": "测试与诊断",
    "suimi8/dsh-cost-ledger": "成本与用量",
    "suimi8/dsh-test-runner": "测试与诊断",
    "suntianc/dsh-codex-auth": "模型与推理",
    "sybolization/agent-jit": "Agent 与自动化",
    "syy-shark/dsh-music-plugin": "趣味与娱乐",
    "t1yOS/t1y-skills": "开发与工程",
    "tanf1ng/dsh-tool-hackernews": "浏览器与远程",
    "tappass/dsh-governance": "Agent 与自动化",
    "taxueseek/argo": "浏览器与远程",
    "techysy/deepseek-harness-fnos": "桌面客户端",
    "tianji-qingtian/dsh-model-router": "模型与推理",
    "titanwings/colleague-skill": "趣味与娱乐",
    "titanwings/dsh-automation": "Agent 与自动化",
    "titanwings/dsh-better-browser": "浏览器与远程",
    "titanwings/dsh-plannotator": "输入与提示词",
    "tkr520521/dsh-agent-teams": "Agent 与自动化",
    "tkr520521/dsh-repo-analyzer": "开发与工程",
    "tkr520521/dsh-team-runner": "Agent 与自动化",
    "tree201/dsh-capability-inspector": "测试与诊断",
    "tttnny/DSH-Launcher": "桌面客户端",
    "turtle1999/turtle-ui": "界面与体验",
    "unknowbug/RE-Framework": "开发与工程",
    "unknowbug/anchorlaw": "测试与诊断",
    "unnnnoooo/dsh-cue-plugin": "记忆与上下文",
    "userInner/dsh-academic-research": "研究与知识",
    "vcxmug/dsh-enhance": "浏览器与远程",
    "vexpaer/ContextGate": "记忆与上下文",
    "vibeinging/dsh-agent-budget": "成本与用量",
    "vibeinging/dsh-tool-search": "开发与工程",
    "vibeinging/dsh-trace": "测试与诊断",
    "vibeinging/dsh-turn-navigator": "界面与体验",
    "vibeinging/dsh-work": "开发与工程",
    "vlln/dsh-loop": "Agent 与自动化",
    "vlln/dsh-navbar": "界面与体验",
    "vlln/dsh-task-status": "界面与体验",
    "vlln/plugin-registry": "开发与工程",
    "vlln/whale-girl": "趣味与娱乐",
    "vvlife/awesome-deepseek-harness-plugins": "开发与工程",
    "vvlife/dsh-agnes-paseo": "模型与推理",
    "walavave/dsh-git": "开发与工程",
    "walkinglabs/awesome-deepseek-harness-plugins": "开发与工程",
    "wangshunnn/oh-my-dsh": "开发与工程",
    "wangxiang0605qvq/dsh-auto-compact": "记忆与上下文",
    "wangxiang0605qvq/dsh-deepseek-balance": "成本与用量",
    "wangyang10/image-vision": "视觉与图像",
    "weijiafu14/dsh-remote-sandbox": "浏览器与远程",
    "weijiafu14/pi2dsh": "开发与工程",
    "wellorbetter/dsh-product-delivery-workflow": "Agent 与自动化",
    "wess09/DeepSeekHarnessDesktop": "桌面客户端",
    "white0dew/awesome-dsh-plugins": "开发与工程",
    "whiteguo233/OpenBiliClaw": "Agent 与自动化",
    "whiteguo233/dsh-cc-connect": "浏览器与远程",
    "whiteguo233/dsh-openbiliclaw": "Agent 与自动化",
    "whitelonng/dshcode": "桌面客户端",
    "why913/dshx": "开发与工程",
    "whyihaveyou/dsh-suite": "开发与工程",
    "william-jin-cmu/dsh-artifact": "开发与工程",
    "william-jin-cmu/dsh-companion": "桌面客户端",
    "william-jin-cmu/dsh-evolve": "Agent 与自动化",
    "william-jin-cmu/dsh-stickers": "趣味与娱乐",
    "william-jin-cmu/dsh-vision": "视觉与图像",
    "wingoo/codex-plugin-dsh": "模型与推理",
    "wly8691-jpg/knowlp-rag": "记忆与上下文",
    "wssfk12138/dsh-wechat-notify": "消息与通知",
    "wulun811/LiuHe": "开发与工程",
    "wuwangmao/dsh-qwen-multimodal": "视觉与图像",
    "wuxiangru915/dsh-review-loop": "测试与诊断",
    "wuyuanjiang1/dsh2wechat": "消息与通知",
    "xDer666/dsh-mobile-nav": "界面与体验",
    "xiangshangya/deepseek-harness-desktop": "桌面客户端",
    "xiaohai-78/Top": "数据与可视化",
    "xiaomiba0904/dsh-obsidian-export": "记忆与上下文",
    "xiaoshihou514/dsh-tui": "终端与 TUI",
    "xiaoshihou514/dsh-vision": "视觉与图像",
    "xiaoshihou514/dsh-weixin": "消息与通知",
    "xiaoxiao-svg/delivery-review-dsh-plugin": "Agent 与自动化",
    "xiaoyuxiaoyuqwq/dsh-desktop": "桌面客户端",
    "xinCodes/deepseek-billing-plugin": "成本与用量",
    "xing-shuyin/ds-web-ui": "界面与体验",
    "xingyingyuzhui/dsh-updater-ui": "开发与工程",
    "xinmo114514/dsh-usage-widget": "成本与用量",
    "xu1132/dsh-plugin-browser": "浏览器与远程",
    "xu1132/dsh-plugin-hello": "开发与工程",
    "xuender/dsh-history": "输入与提示词",
    "yan9651688/dsh-file-checksum": "安全与隐私",
    "yangYzc/dsh-plugin-quote-reply": "输入与提示词",
    "yanglongyun/dsh-ramify": "开发与工程",
    "yangzhe1003/dsh-web-search-firecrawl": "浏览器与远程",
    "ycp424c/dsh-browser-bridge": "浏览器与远程",
    "ycp424c/dsh-luna-vision-bridge": "视觉与图像",
    "yequ172672/dsh-codex-subscription": "模型与推理",
    "yjh051108/dsh-super-injector": "开发与工程",
    "yjm110517/content-to-editable-ppt-skill": "开发与工程",
    "yjm110517/visual-to-editable-ppt-skill": "开发与工程",
    "ylwl1997/noatmark-dsh-plugin": "安全与隐私",
    "yoke233/dsh-openai-codex-auth": "模型与推理",
    "yoke233/dsh-pixel-whale": "趣味与娱乐",
    "yoke233/dsh-prime-agent": "Agent 与自动化",
    "yoke233/dsh-tool-monitor": "开发与工程",
    "youjiaqi421/dsh-plugin-workspace-rules": "输入与提示词",
    "ysr666/dsh-vision-router": "视觉与图像",
    "yuezengwu/dsh-explain": "研究与知识",
    "yumimanji/dsh-ui-spec": "开发与工程",
    "yuukiLike/zeromd": "开发与工程",
    "yuxino/dsh-blue-whale-maid": "趣味与娱乐",
    "yuzi-ska/DSH-Chrome-devtools": "浏览器与远程",
    "yweilai77-dev/dsh-plugin-cost": "成本与用量",
    "yyh-001/dsh-companion": "趣味与娱乐",
    "yyh-001/dsh-expression": "趣味与娱乐",
    "zcx369658780/governed-workflow-for-dsh": "Agent 与自动化",
    "zenx0x/allinluna": "Agent 与自动化",
    "zevorn/dsh-humanize": "开发与工程",
    "zhang66633/dsh-plugin-installer": "开发与工程",
    "zhangzujian/dsh-same-mode-sandbox-noop": "开发与工程",
    "zhaoolee/notes": "开发与工程",
    "zhaoscsc/dsh-wikilink": "输入与提示词",
    "zhouzhencheng07/dsh-tavily-search": "浏览器与远程",
    "zhu1090093659/dsh-web-ui": "界面与体验",
    "zimixvx/dsh-archive-manager": "开发与工程",
    "zimzaza4/dsh-bash-win": "开发与工程",
    "zjl88858/dsh-huadongbianzuqi": "趣味与娱乐",
    "zp-home/dsh-recommend": "数据与可视化",
    "zsyu9779/dsh-desktop": "桌面客户端",
    "zzh-newlearner/dsh-postmortem": "测试与诊断",
    "KirschBluteX/engineer-software": "开发与工程",
    "318197375/dsh-bottom-stats": "数据与可视化",
    "NinjaSln-labs/dsh-session-health": "测试与诊断",

    "dpskh/dsh-a2a": "Agent 与自动化",
    "dpskh/dsh-rewind": "记忆与上下文",
    "hnmrxz/dsh-plugin-sysmon": "数据与可视化",
    "hnmrxz/dsh-plugin-usage-dashboard": "成本与用量",
    "hurry060215-tech/dsh-api-usage-bar": "成本与用量",
    "Mintcolour/dsh-sidechat": "界面与体验",
    "mouliangyu/dsh-plugins": "开发与工程",
    "orxz/deepseek-harness-themes": "界面与体验",
    "wink-run/tokenbank": "模型与推理",

    "dpskh/dsh-checkpoint": "记忆与上下文",
    "NinjaSln-labs/dsh-plugins": "开发与工程",
    "Shmilyol/galgame-skin": "界面与体验",
    "zibo2025/dsh-agent-mesh": "Agent 与自动化",
    "Tabbit-Browser/dsh-plugin": "浏览器与远程",
}
TOPIC_MANUAL = {k.lower(): v for k, v in TOPIC_MANUAL.items()}


# Generic guard: drop any entry whose note references the test phase.
# \u5185\u6d4b is the escaped form of the blocked wording (kept out of source text).
TEST_PHASE = re.compile("\u5185\u6d4b|beta", re.I)

def is_public(r):
    name = r.get("name", "?")
    if r.get("hide") or name in DROP_REPOS:
        return False
    if name in NOTE_REWRITES:
        return True
    note = r.get("note") or r.get("description") or ""
    return not TEST_PHASE.search(note)

def note_for(r):
    name = r.get("name", "?")
    if name in NOTE_REWRITES:
        return NOTE_REWRITES[name]
    return (r.get("note") or r.get("description") or "").strip()

def display_name(r):
    return NAME_REWRITES.get(r.get("name"), r.get("name", "?"))

def url_for(r):
    return URL_REWRITES.get(r.get("name"), r.get("url", "#"))


def main():
    token = None
    url = "https://raw.githubusercontent.com/dsh-external/hub/main/catalog.json"
    if len(sys.argv) > 1 and sys.argv[1] != "-":
        token = sys.argv[1]
    elif len(sys.argv) > 1 and sys.argv[1] == "-":
        token = None
    try:
        cat = fetch(url, token)
        topic_repos = fetch_topic_repos(token)
        fetched_topics = len(topic_repos)
        topic_urls = {(r.get("html_url") or "").rstrip("/").lower() for r in topic_repos}
        manual = [dict(r) for r in EXTRA_TOPIC_REPOS if (r["html_url"].rstrip("/").lower()) not in topic_urls]
        topic_repos = topic_repos + manual
    except Exception as e:
        print(f"fetch failed: {e}", file=sys.stderr)
        return 1

    cats = cat.get("categories", {})
    repos = cat.get("repos", [])
    listed = sum(1 for r in repos if is_public(r))
    hub_urls = {
        url_for(r).rstrip("/").lower()
        for r in repos
        if r.get("url")
    }
    topic_missing = [
        r for r in topic_repos
        if (r.get("html_url") or "").rstrip("/").lower() not in hub_urls
    ]

    out = ["# 完整目录（自动生成）", ""]
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    out.append(f"> 汇集 [dsh-external/hub](https://github.com/dsh-external/hub) 的 `catalog.json` 与 GitHub 公开 [dsh-plugin Topic](https://github.com/topics/dsh-plugin) 的全量生态索引 · 生成于 {now}")
    out.append(f"> 精选列表见 [README](README.md)；本页为公开生态全量索引（{listed} hub 仓库 + {fetched_topics} 公开 topic 仓库{f' + {len(manual)} 手动补充' if manual else ''}）")
    out.append("")

    # 分类顺序
    ordered = sorted(cats.items(), key=lambda kv: kv[1].get("order", 99))
    by_cat = {}
    for r in repos:
        if not is_public(r):
            continue
        by_cat.setdefault(r.get("category", "_uncategorized"), []).append(r)

    for cid, meta in ordered:
        title = meta.get("title", cid)
        emoji = meta.get("emoji", "")
        items = by_cat.get(cid, [])
        if not items:
            continue
        out.append(f"## {emoji} {title}（{len(items)}）")
        out.append("")
        out.append("| 仓库 | 描述 |")
        out.append("|---|---|")
        for r in sorted(items, key=lambda x: x.get("name", "")):
            name = display_name(r)
            desc = note_for(r).replace("|", "\\|")
            out.append(f"| [{name}]({url_for(r)}) | {desc} |")
        out.append("")

    uncat = by_cat.get("_uncategorized", [])
    if uncat:
        out.append(f"## 未分类（{len(uncat)}）")
        out.append("")
        out.append("| 仓库 | 描述 |")
        out.append("|---|---|")
        for r in sorted(uncat, key=lambda x: x.get("name", "")):
            desc = note_for(r).replace("|", "\\|")
            out.append(f"| [{display_name(r)}]({url_for(r)}) | {desc} |")
        out.append("")

    # 插件集（collections）
    collections = cat.get("collections", {})
    if collections:
        out.append("## 插件集")
        out.append("")
        for cname, cdata in collections.items():
            plugins = cdata.get("plugins", [])
            if not plugins:
                continue
            out.append(f"### {cname}")
            out.append("")
            out.append("| 插件 | 描述 |")
            out.append("|---|---|")
            for p in plugins:
                if TEST_PHASE.search(p.get("description") or ""):
                    continue
                desc = (p.get("description") or "").strip().replace("|", "\\|")
                src = p.get("source", "")
                out.append(f"| `{p.get('id','?')}` | {desc} · `{src}` |")
            out.append("")

    if topic_missing:
        out.append(f"## 🌐 公开插件 Topic（{len(topic_missing)}）")
        out.append("")
        out.append(
            f"> 来自 GitHub 公开 [dsh-plugin Topic](https://github.com/topics/dsh-plugin)；"
            f"共发现 {fetched_topics} 个仓库{f'，另有 {len(manual)} 个为维护者手动补充' if manual else ''}，上方 hub 目录未覆盖的公开仓库列于此处。"
        )
        out.append("")

        # category order (curated)
        CATEGORY_ORDER = [
            "界面与体验", "桌面客户端", "终端与 TUI", "输入与提示词",
            "浏览器与远程", "记忆与上下文", "消息与通知", "视觉与图像",
            "模型与推理", "成本与用量", "数据与可视化", "测试与诊断",
            "安全与隐私", "Agent 与自动化", "开发与工程", "研究与知识",
            "趣味与娱乐", "其他",
        ]
        def topic_category(r):
            full = (r.get("full_name") or r.get("name") or "").lower()
            return TOPIC_MANUAL.get(full, "其他")

        by_cat = {}
        for r in topic_missing:
            by_cat.setdefault(topic_category(r), []).append(r)

        for cat in CATEGORY_ORDER:
            items = by_cat.get(cat)
            if not items:
                continue
            out.append(f"### {cat}（{len(items)}）")
            out.append("")
            out.append("| 仓库 | 描述 |")
            out.append("|---|---|")
            for r in sorted(items, key=lambda x: x.get("full_name", "").lower()):
                name = r.get("full_name", r.get("name", "?"))
                desc = (r.get("description") or "").strip() or "暂无描述"
                desc = desc.replace("|", "\\|")
                out.append(f"| [{name}]({r.get('html_url', '#')}) | {desc} |")
            out.append("")

    out.append("---")
    out.append(f"*Generated {datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}*")
    open("CATALOG.md", "w").write("\n".join(out))
    print(
        f"CATALOG.md written: {len(out)} lines, {listed} hub repos, "
        f"{len(topic_repos)} public topic repos ({len(topic_missing)} added)"
    )
    return 0

if __name__ == "__main__":
    sys.exit(main())
